### ISSUE TITLE
Publish packages on pull request

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#22]
Not sure what the best CI solution is, but it would be nice to automatically publish to NPM from a Github action or something like that.

**Comment by cmaycumber** [comment]
I'm a big fan of GitHub actions. This looks like a prebuilt one that handles it: https://github.com/marketplace/actions/publish-to-npm

**Comment by nandorojo** [comment]
Sweet

**Comment by nandorojo** [comment]
any idea how to run `yarn prepare` beforehand?

**Comment by cmaycumber** [comment]
Can't the commands just run beforehand?

For example, here's some potentially how the YAML would look:

```
# Github workflow for running the build process for the vitruly website
# this workflow will only run when a push is made to either the dev branch
# or the master branch

name: npm-publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: prepare
         run: yarn prepare
Other steps from:  https://github.com/marketplace/actions/publish-to-npm goes here
```
